type = "card"
title = "Services"
description = "Professional services and community involvement."

[[items]]
title = "Reviewer"
subtitle = "Science and Technology for the Built Environment journal; ASHRAE conference"
date = "2023 - Present"

[[items]]
title = "Officer - Web Master"
subtitle = "HRAE Texas A&M Student Chapter"
date = "Fall 2023 - Spring 2025"

[[items]]
title = "Student Member"
subtitle = "ASHRAE and ASHRAE Texas A&M Student Chapter"
date = "2023 - Present"

